/**
 * UCLA majors list — sourced from ACM membership-portal-ui/lib/config.ts (Fall 2023 snapshot).
 * Kept alphabetical for binary-search readability in the dropdown.
 */
export const UCLA_MAJORS: readonly string[] = [
  'Aerospace Engineering',
  'African American Studies',
  'African and Middle Eastern Studies',
  'American Indian Studies',
  'American Literature and Culture',
  'Ancient Near East and Egyptology',
  'Anthropology',
  'Arabic',
  'Architectural Studies',
  'Art',
  'Art History',
  'Asian American Studies',
  'Asian Humanities',
  'Asian Languages and Linguistics',
  'Asian Religions',
  'Asian Studies',
  'Astrophysics',
  'Atmospheric and Oceanic Sciences',
  'Atmospheric and Oceanic Sciences/Mathematics',
  'Biochemistry',
  'Bioengineering',
  'Biology',
  'Biophysics',
  'Business Economics',
  'Central and East European Languages and Cultures',
  'Chemical Engineering',
  'Chemistry',
  'Chemistry/Materials Science',
  'Chicana and Chicano Studies',
  'Chinese',
  'Civil Engineering',
  'Classical Civilization',
  'Climate Science',
  'Cognitive Science',
  'Communication',
  'Comparative Literature',
  'Computational and Systems Biology',
  'Computer Engineering',
  'Computer Science',
  'Computer Science and Engineering',
  'Dance',
  'Data Theory',
  'Design | Media Arts',
  'Disability Studies',
  'Earth and Environmental Science',
  'Ecology, Behavior, and Evolution',
  'Economics',
  'Education and Social Transformation',
  'Electrical Engineering',
  'English',
  'Environmental Science',
  'Ethnomusicology',
  'European Language and Transcultural Studies',
  'European Languages and Transcultural Studies with French and Francophone',
  'European Languages and Transcultural Studies with German',
  'European Languages and Transcultural Studies with Italian',
  'European Languages and Transcultural Studies with Scandinavian',
  'European Studies',
  'Film and Television',
  'Gender Studies',
  'Geography',
  'Geography/Environmental Studies',
  'Geology',
  'Geology/Engineering Geology',
  'Geophysics',
  'Global Jazz Studies',
  'Global Studies',
  'Greek',
  'Greek and Latin',
  'History',
  'Human Biology and Society',
  'Individual Field of Concentration',
  'Individual Field of Concentration in the Arts and Architecture',
  'Individual Field of Concentration in Theater, Film and Television',
  'International Development Studies',
  'Iranian Studies',
  'Japanese',
  'Jewish Studies',
  'Korean',
  'Labor Studies',
  'Latin',
  'Latin American Studies',
  'Linguistics',
  'Linguistics and Anthropology',
  'Linguistics and Asian Languages and Cultures',
  'Linguistics and Computer Science',
  'Linguistics and English',
  'Linguistics and Philosophy',
  'Linguistics and Psychology',
  'Linguistics and Spanish',
  'Linguistics, Applied',
  'Marine Biology',
  'Materials Engineering',
  'Mathematics',
  'Mathematics for Teaching',
  'Mathematics of Computation',
  'Mathematics, Applied',
  'Mathematics, Financial Actuarial',
  'Mathematics/Applied Science',
  'Mathematics/Economics',
  'Mechanical Engineering',
  'Microbiology, Immunology, and Molecular Genetics',
  'Middle Eastern Studies',
  'Molecular, Cell, and Developmental Biology',
  'Music Composition',
  'Music Education',
  'Music Industry',
  'Music Performance',
  'Musicology',
  'Neuroscience',
  'Nordic Studies',
  'Nursing',
  'Philosophy',
  'Physics',
  'Physiological Science',
  'Political Science',
  'Portuguese and Brazilian Studies',
  'Psychobiology',
  'Psychology',
  'Public Affairs',
  'Public Health',
  'Religion, Study of',
  'Russian Language and Literature',
  'Russian Studies',
  'Sociology',
  'Southeast Asian Studies',
  'Spanish',
  'Spanish and Community and Culture',
  'Spanish and Linguistics',
  'Spanish and Portuguese',
  'Statistics and Data Science',
  'Theater',
  'Undeclared Engineering and Applied Science',
  'Undeclared Humanities',
  'Undeclared Life Sciences',
  'Undeclared Physical Sciences',
  'Undeclared Social Sciences',
  'World Arts and Cultures',
];

/**
 * Expected graduation years — current year through current year + 6.
 * Recomputed per call so the list stays correct as time passes.
 */
export function getGradYearOptions(): number[] {
  const thisYear = new Date().getFullYear();
  return Array.from({ length: 6 }, (_, i) => thisYear + i);
}
